services:
  database:
    command: ["postgres", "-c", "log_statement=all", "-c", "log_destination=stderr"]
    image: postgres:latest
    platform: linux/amd64
    environment:
      POSTGRES_USER: master
      POSTGRES_PASSWORD: master
      POSTGRES_DB: scraper
    # networks:
    #   - bridge
    ports:
      - "3542:5432"
    volumes:
      - ./src/database/schema.sql:/docker-entrypoint-initdb.d/1_schema.sql
      # - ./src/database/staticData/staticData.sql:/docker-entrypoint-initdb.d/2_staticData.sql
      # - pgdata:/var/lib/postgresql/data
      # - ./extensions.sql:/docker-entrypoint-initdb.d/1_extensions.sql

volumes:
  pgdata: